export const ACTION_TYPES = {
    NOTE: {
        INIT: "NOTE/INIT",
        INIT_NEW: "NOTE/INIT_NEW",
        TOGGLE_PIN: "NOTE/TOGGLE_PIN",
        TOGGLE_PUBLIC: "NOTE/TOGGLE_PUBLIC",
        UPDATE_PUBLIC: "NOTE/UPDATE_PUBLIC"
    },
    CONTENT: {
        UPDATE_CURRENT: 'CONTENT/UPDATE_CURRENT',
        SET_ORIGINAL: "CONTENT/SET_ORIGINAL",
        DISCARD_CHANGES: "CONTENT/DISCARD_CHANGES",
        RESET_CONTENT: "RESET_CONTENT"
    },
    STATUS: {
        UPDATE: 'STATUS/UPDATE',
        TOGGLE_EDIT_MODE: 'STATUS/TOGGLE_EDIT_MODE'
    }
};
