export const ACTION_TYPES = {
    VERSION: {
        INIT: "VERSION/INIT",
        RESTORE: "VERSION/RESTORE",
        SET_FULL_CONTENT: "VERSION/SET_FULL_CONTENT"
    },
    STATUS: {
        INIT_LOADING: "STATUS/INIT_LOADING",
        FULL_CONTENT_LOADING: 'STATUS/ FULL_CONTENT_LOADING',
        LOADING: 'STATUS/LOADING'
    }
};
