export const ACTION_TYPES = Object.freeze({
    UPDATE_GENERAL_ACCESS: 'UPDATE_GENERAL_ACCESS',
    SET_GENERAL_ACCESS: 'SET_GENERAL_ACCESS',
    ADD_NEW_COLLABORATOR: 'ADD_NEW_COLLABORATOR',
    REMOVE_NEW_COLLABORATOR: 'REMOVE_NEW_COLLABORATOR',
    CLEAR_NEW_COLLABORATOR: "CLEAR_NEW_COLLABORATOR",
    UPDATE_COLLABORATOR: 'UPDATE_COLLABORATOR',
    REMOVE_COLLABORATOR: 'REMOVE_COLLABORATOR',
    SET_NEW_COLLABORATOR_NOTIFY: 'SET_NEW_COLLABORATOR_NOTIFY',
    SET_NEW_COLLABORATOR_MESSAGE: 'SET_NEW_COLLABORATOR_MESSAGE',
    SET_NEW_COLLABORATOR_ROLE: 'SET_NEW_COLLABORATOR_ROLE',
    INITIAL_DATA_LOADED: "INITIAL_DATA_LOADED",
    APPLY_CHANGES_TO_COLLABORATORS: "APPLY_CHANGES_TO_COLLABORATORS",
    UPDATE_STATUS: "UPDATE_STATUS"
});
