// Object for HTTP status codes
const HttpStatusCode = Object.freeze({
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    METHOD_NOT_ALLOWED: 405,
    REQUEST_TIMEOUT: 408,
    CONFLICT: 409,
    GONE: 410,
    LENGTH_REQUIRED: 411,
    PRECONDITION_FAILED: 412,
    PAYLOAD_TOO_LARGE: 413,
    URI_TOO_LONG: 414,
    UNSUPPORTED_MEDIA_TYPE: 415,
    RANGE_NOT_SATISFIABLE: 416,
    EXPECTATION_FAILED: 417,
    IM_A_TEAPOT: 418, // I'm a teapot (RFC 2324)
    UNPROCESSABLE_ENTITY: 422,
    LOCKED: 423,
    FAILED_DEPENDENCY: 424,
    TOO_EARLY: 425,
    UPGRADE_REQUIRED: 426,
    PRECONDITION_REQUIRED: 428,
    TOO_MANY_REQUESTS: 429,
    REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
    UNAVAILABLE_FOR_LEGAL_REASONS: 451,
    INTERNAL_SERVER_ERROR: 500,
    NOT_IMPLEMENTED: 501,
    BAD_GATEWAY: 502,
    SERVICE_UNAVAILABLE: 503,
    GATEWAY_TIMEOUT: 504,
    HTTP_VERSION_NOT_SUPPORTED: 505,
    VARIANT_ALSO_NEGOTIATES: 506,
    INSUFFICIENT_STORAGE: 507,
    LOOP_DETECTED: 508,
    NOT_EXTENDED: 510,
    NETWORK_AUTHENTICATION_REQUIRED: 511,
    CONNECTION_ABORTED: 'ECONNABORTED',
});

// Object for messages corresponding to status codes
const HttpStatusMessages = Object.freeze({
    200: "OK - The request has succeeded, and the response contains the requested data.",
    201: "Created - The request has been fulfilled, and a new resource has been created.",
    400: "Bad Request - The server could not understand the request due to invalid syntax or missing parameters.",
    401: "Unauthorized - The client must authenticate to access the requested resource.",
    403: "Forbidden - The client does not have permission to access the requested resource.",
    404: "Not Found - The server cannot find the requested resource, it may have been moved or deleted.",
    405: "Method Not Allowed - The HTTP method used is not supported by the resource.",
    408: "Request Timeout - The server timed out while waiting for the request to complete.",
    409: "Conflict - The request could not be completed due to a conflict with the current state of the resource.",
    410: "Gone - The requested resource is no longer available and has been permanently removed.",
    411: "Length Required - The server refuses to process the request without a specified Content-Length.",
    412: "Precondition Failed - The server cannot process the request due to failed preconditions in the headers.",
    413: "Payload Too Large - The request entity is too large to be processed by the server.",
    414: "URI Too Long - The URI provided in the request is too long for the server to process.",
    415: "Unsupported Media Type - The media type of the request is not supported by the server.",
    416: "Range Not Satisfiable - The requested range in the header field is not valid for the resource.",
    417: "Expectation Failed - The server cannot fulfill the expectation specified in the request's Expect header.",
    418: "I'm a Teapot - The server is a teapot and cannot brew coffee as per RFC 2324.",
    422: "Unprocessable Entity - The request was well-formed but cannot be processed due to semantic errors.",
    423: "Locked - The resource being accessed is locked and cannot be modified.",
    424: "Failed Dependency - The request failed due to the failure of a previous request it depended on.",
    425: "Too Early - The server is unwilling to process the request due to a risk of it being replayed.",
    426: "Upgrade Required - The client should upgrade to a different protocol to proceed.",
    428: "Precondition Required - The server requires the request to be conditional.",
    429: "Too Many Requests - The client has sent too many requests in a short period and is being rate-limited.",
    431: "Request Header Fields Too Large - The request's header fields are too large for the server to process.",
    451: "Unavailable For Legal Reasons - The requested resource is unavailable due to legal restrictions.",
    500: "Internal Server Error - The server encountered an unexpected condition that prevented it from fulfilling the request.",
    501: "Not Implemented - The server does not support the functionality required to fulfill the request.",
    502: "Bad Gateway - The server, acting as a gateway or proxy, received an invalid response from the upstream server.",
    503: "Service Unavailable - The server is temporarily unable to handle the request due to overload or maintenance.",
    504: "Gateway Timeout - The server, acting as a gateway or proxy, did not receive a timely response from the upstream server.",
    505: "HTTP Version Not Supported - The server does not support the HTTP version used in the request.",
    506: "Variant Also Negotiates - The server has an internal configuration error and cannot negotiate the requested variant.",
    507: "Insufficient Storage - The server cannot store the representation required to complete the request.",
    508: "Loop Detected - The server detected an infinite loop while processing the request.",
    510: "Not Extended - Further extensions to the request are needed for the server to fulfill it.",
    511: "Network Authentication Required - The client needs to authenticate to gain network access.",
    ECONNABORTED: "Connection Aborted - The connection was aborted due to timeout or server issues."
});


module.exports = {HttpStatusCode, HttpStatusMessages};
