// Object for HTTP status codes
const httpCodes = Object.freeze({
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    METHOD_NOT_ALLOWED: 405,
    REQUEST_TIMEOUT: 408,
    CONFLICT: 409,
    GONE: 410,
    LENGTH_REQUIRED: 411,
    PRECONDITION_FAILED: 412,
    PAYLOAD_TOO_LARGE: 413,
    URI_TOO_LONG: 414,
    UNSUPPORTED_MEDIA_TYPE: 415,
    RANGE_NOT_SATISFIABLE: 416,
    EXPECTATION_FAILED: 417,
    IM_A_TEAPOT: 418, // I'm a teapot (RFC 2324)
    UNPROCESSABLE_ENTITY: 422,
    LOCKED: 423,
    FAILED_DEPENDENCY: 424,
    TOO_EARLY: 425,
    UPGRADE_REQUIRED: 426,
    PRECONDITION_REQUIRED: 428,
    TOO_MANY_REQUESTS: 429,
    REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
    UNAVAILABLE_FOR_LEGAL_REASONS: 451,
    INTERNAL_SERVER_ERROR: 500,
    NOT_IMPLEMENTED: 501,
    BAD_GATEWAY: 502,
    SERVICE_UNAVAILABLE: 503,
    GATEWAY_TIMEOUT: 504,
    HTTP_VERSION_NOT_SUPPORTED: 505,
    VARIANT_ALSO_NEGOTIATES: 506,
    INSUFFICIENT_STORAGE: 507,
    LOOP_DETECTED: 508,
    NOT_EXTENDED: 510,
    NETWORK_AUTHENTICATION_REQUIRED: 511,
    CONNECTION_ABORTED: 'ECONNABORTED',
});

// Object for messages corresponding to status codes
const httpMessages = Object.freeze({
    200: "OK: The request has succeeded.",
    201: "Created: The request has been fulfilled and resulted in a new resource being created.",
    400: "Bad Request: The server could not understand the request due to invalid syntax.",
    401: "Unauthorized: The client must authenticate itself to get the requested response.",
    403: "Forbidden: The client does not have access rights to the content.",
    404: "Not Found: The server cannot find the requested resource.",
    405: "Method Not Allowed: The request method is known by the server but is not supported by the target resource.",
    408: "Request Timeout: The server timed out waiting for the request.",
    409: "Conflict: The request could not be completed due to a conflict with the current state of the target resource.",
    410: "Gone: The requested resource is no longer available and will not be available again.",
    411: "Length Required: The server refuses to accept the request without a defined Content-Length.",
    412: "Precondition Failed: One or more conditions in the request header fields evaluated to false.",
    413: "Payload Too Large: The request entity is larger than limits defined by the server.",
    414: "URI Too Long: The URI provided was too long for the server to process.",
    415: "Unsupported Media Type: The media type of the requested data is not supported by the server.",
    416: "Range Not Satisfiable: The range specified by the Range header field is not valid.",
    417: "Expectation Failed: The server cannot meet the expectations of the Expect request-header field.",
    418: "I'm a Teapot: The server is a teapot and cannot brew coffee. (RFC 2324)",
    422: "Unprocessable Entity: The request was well-formed but the server was unable to process it.",
    423: "Locked: The resource that is being accessed is locked.",
    424: "Failed Dependency: The request failed due to failure of a previous request.",
    425: "Too Early: The server is unwilling to risk processing a request that might be replayed.",
    426: "Upgrade Required: The client should switch to a different protocol.",
    428: "Precondition Required: The server requires the request to be conditional.",
    429: "Too Many Requests: The user has sent too many requests in a given amount of time.",
    431: "Request Header Fields Too Large: The server is unwilling to process the request because its header fields are too large.",
    451: "Unavailable For Legal Reasons: The resource is unavailable for legal reasons.",
    500: "Internal Server Error: The server has encountered a situation it doesn't know how to handle.",
    501: "Not Implemented: The server does not support the functionality required to fulfill the request.",
    502: "Bad Gateway: The server, while acting as a gateway or proxy, got an invalid response from the upstream server.",
    503: "Service Unavailable: The server is not ready to handle the request, often due to being overloaded or down for maintenance.",
    504: "Gateway Timeout: The server, while acting as a gateway or proxy, did not receive a timely response from the upstream server.",
    505: "HTTP Version Not Supported: The HTTP version used in the request is not supported by the server.",
    506: "Variant Also Negotiates: The server has an internal configuration error and the requested variant is also negotiable.",
    507: "Insufficient Storage: The server is unable to store the representation needed to complete the request.",
    508: "Loop Detected: The server detected an infinite loop while processing the request.",
    510: "Not Extended: Further extensions to the request are required for the server to fulfill it.",
    511: "Network Authentication Required: The client needs to authenticate to gain network access.",
    ECONNABORTED: "Connection Aborted: The connection was aborted, possibly due to a timeout or server issue.",
});

module.exports = {httpCodes, httpMessages};
